name: Build EXE from Python

on:
  push:
    branches:
      - main  # 推送到 main 分支时触发
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 使用合适的 Python 版本

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # 4. 构建 EXE 文件
    - name: Build EXE file
      run: |
        pyinstaller --clean --onefile --hidden-import=all --collect-all=all backend.py

    # 5. 上传 EXE 文件作为工件
    - name: Upload EXE file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-exe
        path: dist/backend.exe
